"use client";

import Link from "next/link";
import { useLang, type Lang } from "@/contexts/lang-context";

type Copy = {
  title: string;
  back: string;
  updated: string;
  admin: string;
  warning: string;
  adminText: string;
  data: string;
  dataText: string;
  location: string;
  locationText: string;
  storage: string;
  storageText: string;
  services: string;
  servicesText: string;
  legal: string;
  legalText: string;
  rights: string;
  rightsText: string;
  changes: string;
  changesText: string;
  draft: string;
};

const common = {
  gps: "GPS",
  owner: "Kacper Pasiński",
  email: "mypassionsiswindsurfing@duck.com",
};

const COPY: Record<Lang, Copy> = {
  pl: {
    title: "Polityka prywatności", back: "Wróć do aplikacji", updated: "Ostatnia aktualizacja: 10 lipca 2026 r.",
    admin: "1. Administrator danych", warning: "Przed publicznym udostępnieniem uzupełnij tę sekcję pełną nazwą administratora, adresem oraz adresem e-mail do spraw prywatności.", adminText: `Administratorem danych jest: ${common.owner}, kontakt: ${common.email}.`,
    data: "2. Jakie dane przetwarzamy", dataText: "Przetwarzamy lokalizację urządzenia podczas aktywnego trybu jazdy, przekazany plik lub link trasy, ustawienia zapisane w przeglądarce, dane konta przy rejestracji oraz podstawowe dane techniczne potrzebne do działania i zabezpieczenia aplikacji.",
    location: "3. Lokalizacja i tryb jazdy", locationText: "Lokalizacja jest pobierana dopiero po kliknięciu „Rozpocznij” i zgodzie przeglądarki. Służy do pokazania użytkownika na mapie, wyliczenia postępu i alertów. Pozycja GPS nie jest wysyłana do naszego API ani zapisywana na naszym serwerze. Zatrzymanie trybu jazdy kończy odczyty.",
    storage: "4. Trasy i pamięć przeglądarki", storageText: "Ostatnia trasa i ustawienia mogą być zapisane lokalnie w przeglądarce, aby odtworzyć je przy kolejnym wejściu. Nie przechowujemy ich na serwerze. Możesz usunąć te dane, czyszcząc dane witryny.",
    services: "5. Usługi zewnętrzne", servicesText: "Aplikacja może korzystać z Open-Meteo, OpenStreetMap/Overpass, Google Maps/BRouter, Supabase, Vercel i Upstash Redis. Dostawcy mogą przetwarzać dane techniczne według własnych polityk. Link Google Maps i trasa służą wyłącznie do importu; GPS nie jest przekazywany tym usługom.",
    legal: "6. Cel i podstawa prawna", legalText: "Dane służą do planowania trasy, prognozy, alertów i obsługi konta. Podstawę prawną należy dobrać do sposobu prowadzenia usługi; dla dobrowolnej lokalizacji stosowana jest zgoda użytkownika, a dla konta może mieć zastosowanie wykonanie umowy.",
    rights: "7. Prawa użytkownika", rightsText: "Możesz żądać dostępu do danych, ich sprostowania, usunięcia lub ograniczenia przetwarzania, a także wnieść sprzeciw, jeśli masz do tego podstawę. W sprawach prywatności skontaktuj się z administratorem. Możesz również złożyć skargę do Prezesa UODO.",
    changes: "8. Zmiany polityki", changesText: "Polityka może być aktualizowana po zmianie aplikacji, sposobu przetwarzania danych lub usług zewnętrznych. Aktualna wersja jest publikowana na tej stronie.",
    draft: "To roboczy wzór informacji dla obecnej wersji aplikacji. Przed komercyjnym lub publicznym uruchomieniem uzupełnij dane administratora i skonsultuj treść z prawnikiem.",
  },
  en: {
    title: "Privacy policy", back: "Back to the app", updated: "Last updated: 10 July 2026", admin: "1. Data controller", warning: "Before making the app public, complete this section with the controller's full name, address and privacy email.", adminText: `Data controller: ${common.owner}, contact: ${common.email}.`, data: "2. Data we process", dataText: "We process device location during active ride mode, a route file or link supplied by the user, browser settings, account data when registration is used, and basic technical data needed to operate and secure the app.", location: "3. Location and ride mode", locationText: "Location is read only after the user clicks “Start” and grants browser permission. It is used to show the rider on the map, calculate progress and show alerts. GPS coordinates are not sent to our API or stored on our server. Stopping ride mode ends location readings.", storage: "4. Routes and browser storage", storageText: "The last route and settings may be stored locally in the browser so they can be restored on the next visit. We do not store them on our server. You can delete them by clearing site data.", services: "5. External services", servicesText: "The app may use Open-Meteo, OpenStreetMap/Overpass, Google Maps/BRouter, Supabase, Vercel and Upstash Redis. Providers may process technical data under their own policies. Google Maps links and routes are used only for import; GPS is not shared with these services.", legal: "6. Purpose and legal basis", legalText: "Data is used to provide route planning, forecasts, alerts and account support. The legal basis must match how the service is operated; voluntary location uses the user's consent, while account support may rely on contract performance.", rights: "7. Your rights", rightsText: "You may request access, correction, deletion or restriction of your data, and object where applicable. Contact the controller for privacy matters. You may also complain to your local data protection authority.", changes: "8. Changes", changesText: "This policy may change when the app, processing activities or external services change. The current version is published on this page.", draft: "This is a working privacy notice for the current app version. Before commercial or public launch, complete the controller details and have the text reviewed by a lawyer.",
  },
  de: {
    title: "Datenschutzerklärung", back: "Zurück zur App", updated: "Letzte Aktualisierung: 10. Juli 2026", admin: "1. Verantwortlicher", warning: "Vor der öffentlichen Freigabe müssen Name, Anschrift und Datenschutz-E-Mail des Verantwortlichen ergänzt werden.", adminText: `Verantwortlicher: ${common.owner}, Kontakt: ${common.email}.`, data: "2. Verarbeitete Daten", dataText: "Wir verarbeiten den Gerätestandort während des aktiven Fahrmodus, eine vom Nutzer angegebene Routendatei oder einen Link, Browsereinstellungen, Kontodaten bei einer Registrierung und technische Daten für Betrieb und Sicherheit.", location: "3. Standort und Fahrmodus", locationText: "Der Standort wird erst nach Klick auf „Start“ und Zustimmung des Browsers gelesen. Er dient der Kartenposition, dem Fortschritt und Warnungen. GPS-Daten werden nicht an unsere API gesendet und nicht auf unserem Server gespeichert. Beim Beenden endet die Abfrage.", storage: "4. Routen und Browserspeicher", storageText: "Die letzte Route und Einstellungen können lokal im Browser gespeichert werden. Wir speichern sie nicht auf unserem Server. Sie können die Website-Daten im Browser löschen.", services: "5. Externe Dienste", servicesText: "Die App kann Open-Meteo, OpenStreetMap/Overpass, Google Maps/BRouter, Supabase, Vercel und Upstash Redis verwenden. Diese Anbieter verarbeiten technische Daten nach ihren eigenen Richtlinien. GPS wird nicht weitergegeben.", legal: "6. Zweck und Rechtsgrundlage", legalText: "Die Daten dienen Routenplanung, Wettervorhersage, Warnungen und Kontoverwaltung. Die Rechtsgrundlage muss zur Nutzung passen; der freiwillige Standort basiert auf Einwilligung, die Kontonutzung kann auf Vertragserfüllung beruhen.", rights: "7. Ihre Rechte", rightsText: "Sie können Auskunft, Berichtigung, Löschung oder Einschränkung verlangen und gegebenenfalls widersprechen. Wenden Sie sich an den Verantwortlichen oder Ihre Datenschutzaufsichtsbehörde.", changes: "8. Änderungen", changesText: "Diese Erklärung kann bei Änderungen der App, Verarbeitung oder externer Dienste aktualisiert werden.", draft: "Dies ist ein Arbeitsentwurf für die aktuelle Version. Ergänzen Sie die Verantwortlichendaten vor der öffentlichen Nutzung und lassen Sie den Text rechtlich prüfen.",
  },
  fr: {
    title: "Politique de confidentialité", back: "Retour à l’application", updated: "Dernière mise à jour : 10 juillet 2026", admin: "1. Responsable du traitement", warning: "Avant la publication, indiquez le nom complet, l’adresse et l’e-mail du responsable.", adminText: `Responsable : ${common.owner}, contact : ${common.email}.`, data: "2. Données traitées", dataText: "Nous traitons la position de l’appareil pendant le mode conduite, le fichier ou lien d’itinéraire fourni, les réglages du navigateur, les données du compte et les données techniques nécessaires au fonctionnement.", location: "3. Position et mode conduite", locationText: "La position est lue après clic sur « Démarrer » et autorisation du navigateur. Elle sert à afficher l’utilisateur, calculer sa progression et afficher des alertes. Les coordonnées GPS ne sont pas envoyées à notre API ni stockées sur notre serveur.", storage: "4. Itinéraires et navigateur", storageText: "Le dernier itinéraire et les réglages peuvent être stockés localement dans le navigateur. Ils ne sont pas stockés sur notre serveur et peuvent être supprimés en effaçant les données du site.", services: "5. Services externes", servicesText: "L’application peut utiliser Open-Meteo, OpenStreetMap/Overpass, Google Maps/BRouter, Supabase, Vercel et Upstash Redis. Ces fournisseurs appliquent leurs propres politiques. La position GPS ne leur est pas transmise.", legal: "6. Finalité et base légale", legalText: "Les données servent à planifier l’itinéraire, fournir la météo, les alertes et gérer le compte. La base légale dépend du service ; la position volontaire repose sur le consentement et le compte peut reposer sur l’exécution d’un contrat.", rights: "7. Vos droits", rightsText: "Vous pouvez demander l’accès, la rectification, l’effacement ou la limitation du traitement et vous opposer lorsque cela s’applique. Contactez le responsable ou votre autorité de protection des données.", changes: "8. Modifications", changesText: "Cette politique peut être mise à jour lorsque l’application, les traitements ou les services changent.", draft: "Ce document est un modèle de travail. Complétez les coordonnées du responsable et faites vérifier le texte avant une utilisation publique.",
  },
  es: {
    title: "Política de privacidad", back: "Volver a la aplicación", updated: "Última actualización: 10 de julio de 2026", admin: "1. Responsable del tratamiento", warning: "Antes de publicar la aplicación, completa el nombre, la dirección y el correo de privacidad del responsable.", adminText: `Responsable: ${common.owner}, contacto: ${common.email}.`, data: "2. Datos que tratamos", dataText: "Tratamos la ubicación del dispositivo durante el modo de viaje, el archivo o enlace de ruta enviado, la configuración del navegador, los datos de la cuenta y datos técnicos necesarios para operar y proteger la aplicación.", location: "3. Ubicación y modo de viaje", locationText: "La ubicación se obtiene después de pulsar «Iniciar» y aceptar el permiso del navegador. Se usa para mostrar al usuario en el mapa, calcular el progreso y mostrar alertas. El GPS no se envía a nuestra API ni se guarda en nuestro servidor.", storage: "4. Rutas y almacenamiento del navegador", storageText: "La última ruta y la configuración pueden guardarse localmente en el navegador. No se almacenan en nuestro servidor y pueden eliminarse borrando los datos del sitio.", services: "5. Servicios externos", servicesText: "La aplicación puede usar Open-Meteo, OpenStreetMap/Overpass, Google Maps/BRouter, Supabase, Vercel y Upstash Redis. Cada proveedor aplica su propia política. La ubicación GPS no se comparte con ellos.", legal: "6. Finalidad y base legal", legalText: "Los datos sirven para planificar rutas, ofrecer previsiones, alertas y gestionar cuentas. La base legal debe ajustarse al servicio; la ubicación voluntaria se basa en el consentimiento y la cuenta puede basarse en la ejecución de un contrato.", rights: "7. Tus derechos", rightsText: "Puedes solicitar acceso, rectificación, eliminación o limitación del tratamiento y oponerte cuando corresponda. Contacta con el responsable o con tu autoridad de protección de datos.", changes: "8. Cambios", changesText: "Esta política puede actualizarse cuando cambien la aplicación, los tratamientos o los servicios externos.", draft: "Este es un modelo de trabajo. Completa los datos del responsable y revisa el texto con un abogado antes del uso público.",
  },
  it: {
    title: "Informativa sulla privacy", back: "Torna all’app", updated: "Ultimo aggiornamento: 10 luglio 2026", admin: "1. Titolare del trattamento", warning: "Prima della pubblicazione completa nome, indirizzo ed e-mail privacy del titolare.", adminText: `Titolare: ${common.owner}, contatto: ${common.email}.`, data: "2. Dati trattati", dataText: "Trattiamo la posizione del dispositivo durante la modalità di viaggio, il file o link del percorso, le impostazioni del browser, i dati dell’account e i dati tecnici necessari al funzionamento e alla sicurezza.", location: "3. Posizione e modalità di viaggio", locationText: "La posizione viene letta dopo il clic su «Avvia» e il consenso del browser. Serve a mostrare l’utente sulla mappa, calcolare il progresso e mostrare avvisi. Il GPS non viene inviato alla nostra API né salvato sul nostro server.", storage: "4. Percorsi e memoria del browser", storageText: "L’ultimo percorso e le impostazioni possono essere salvati localmente nel browser. Non sono memorizzati sul nostro server e possono essere eliminati cancellando i dati del sito.", services: "5. Servizi esterni", servicesText: "L’app può usare Open-Meteo, OpenStreetMap/Overpass, Google Maps/BRouter, Supabase, Vercel e Upstash Redis. I fornitori applicano le proprie policy. La posizione GPS non viene condivisa con loro.", legal: "6. Finalità e base giuridica", legalText: "I dati servono per percorsi, previsioni, avvisi e account. La base giuridica dipende dal servizio; la posizione volontaria si basa sul consenso e l’account può basarsi sull’esecuzione del contratto.", rights: "7. I tuoi diritti", rightsText: "Puoi chiedere accesso, rettifica, cancellazione o limitazione e opporti quando previsto. Contatta il titolare o l’autorità per la protezione dei dati.", changes: "8. Modifiche", changesText: "Questa informativa può essere aggiornata quando cambiano app, trattamenti o servizi esterni.", draft: "Questo è un modello di lavoro. Completa i dati del titolare e fai verificare il testo da un legale prima dell’uso pubblico.",
  },
  cs: {
    title: "Zásady ochrany osobních údajů", back: "Zpět do aplikace", updated: "Poslední aktualizace: 10. července 2026", admin: "1. Správce údajů", warning: "Před zveřejněním doplňte celé jméno, adresu a e-mail správce pro ochranu osobních údajů.", adminText: `Správce: ${common.owner}, kontakt: ${common.email}.`, data: "2. Zpracovávané údaje", dataText: "Zpracováváme polohu zařízení během aktivní jízdy, soubor nebo odkaz na trasu, nastavení prohlížeče, údaje účtu a technické údaje potřebné k provozu a zabezpečení aplikace.", location: "3. Poloha a režim jízdy", locationText: "Poloha se načítá až po kliknutí na „Spustit“ a povolení prohlížeče. Slouží k zobrazení uživatele na mapě, výpočtu postupu a upozornění. GPS se neposílá do našeho API ani neukládá na server.", storage: "4. Trasy a úložiště prohlížeče", storageText: "Poslední trasa a nastavení mohou být uloženy místně v prohlížeči. Na serveru je neukládáme a lze je odstranit vymazáním dat webu.", services: "5. Externí služby", servicesText: "Aplikace může využívat Open-Meteo, OpenStreetMap/Overpass, Google Maps/BRouter, Supabase, Vercel a Upstash Redis. Poskytovatelé mají vlastní zásady. GPS poloha se jim nepředává.", legal: "6. Účel a právní základ", legalText: "Údaje slouží k plánování trasy, předpovědi, upozorněním a účtu. Právní základ musí odpovídat službě; dobrovolná poloha je založena na souhlasu a účet může být založen na plnění smlouvy.", rights: "7. Vaše práva", rightsText: "Můžete požádat o přístup, opravu, výmaz nebo omezení zpracování a případně vznést námitku. Kontaktujte správce nebo místní úřad pro ochranu osobních údajů.", changes: "8. Změny", changesText: "Tyto zásady mohou být aktualizovány při změně aplikace, zpracování nebo externích služeb.", draft: "Jde o pracovní vzor. Před veřejným použitím doplňte údaje správce a nechte text právně zkontrolovat.",
  },
  nl: {
    title: "Privacybeleid", back: "Terug naar de app", updated: "Laatst bijgewerkt: 10 juli 2026", admin: "1. Verwerkingsverantwoordelijke", warning: "Vul vóór openbare publicatie de volledige naam, het adres en het privacy-e-mailadres van de verantwoordelijke in.", adminText: `Verantwoordelijke: ${common.owner}, contact: ${common.email}.`, data: "2. Gegevens die wij verwerken", dataText: "Wij verwerken de apparaatlocatie tijdens de actieve ritmodus, een routebestand of link, browserinstellingen, accountgegevens en technische gegevens die nodig zijn voor werking en beveiliging.", location: "3. Locatie en ritmodus", locationText: "Locatie wordt pas gelezen nadat de gebruiker op ‘Start’ klikt en browser toestemming geeft. De locatie wordt gebruikt voor de kaart, voortgang en waarschuwingen. GPS wordt niet naar onze API gestuurd en niet op onze server opgeslagen.", storage: "4. Routes en browseropslag", storageText: "De laatste route en instellingen kunnen lokaal in de browser worden opgeslagen. Wij bewaren ze niet op onze server. Je kunt ze verwijderen door sitegegevens te wissen.", services: "5. Externe diensten", servicesText: "De app kan Open-Meteo, OpenStreetMap/Overpass, Google Maps/BRouter, Supabase, Vercel en Upstash Redis gebruiken. Deze partijen hebben eigen beleid. GPS wordt niet met hen gedeeld.", legal: "6. Doel en rechtsgrond", legalText: "Gegevens worden gebruikt voor routeplanning, voorspellingen, waarschuwingen en accounts. De rechtsgrond hangt af van de dienst; vrijwillige locatie gebruikt toestemming en accountgebruik kan op overeenkomst berusten.", rights: "7. Jouw rechten", rightsText: "Je kunt toegang, correctie, verwijdering of beperking vragen en bezwaar maken waar dat van toepassing is. Neem contact op met de verantwoordelijke of je privacytoezichthouder.", changes: "8. Wijzigingen", changesText: "Dit beleid kan worden bijgewerkt wanneer de app, verwerking of externe diensten veranderen.", draft: "Dit is een werkversie. Vul de gegevens van de verantwoordelijke in en laat de tekst juridisch controleren vóór openbaar gebruik.",
  },
  pt: {
    title: "Política de privacidade", back: "Voltar à aplicação", updated: "Última atualização: 10 de julho de 2026", admin: "1. Responsável pelo tratamento", warning: "Antes da publicação, preencha o nome completo, endereço e e-mail de privacidade do responsável.", adminText: `Responsável: ${common.owner}, contacto: ${common.email}.`, data: "2. Dados tratados", dataText: "Tratamos a localização do dispositivo durante o modo de viagem, um ficheiro ou link de rota, definições do navegador, dados da conta e dados técnicos necessários ao funcionamento e segurança.", location: "3. Localização e modo de viagem", locationText: "A localização só é lida depois de clicar em ‘Iniciar’ e permitir o acesso no navegador. É usada para mostrar o utilizador no mapa, calcular o progresso e mostrar alertas. O GPS não é enviado para a nossa API nem guardado no servidor.", storage: "4. Rotas e armazenamento do navegador", storageText: "A última rota e as definições podem ser guardadas localmente no navegador. Não as guardamos no servidor e podem ser apagadas ao limpar os dados do site.", services: "5. Serviços externos", servicesText: "A aplicação pode utilizar Open-Meteo, OpenStreetMap/Overpass, Google Maps/BRouter, Supabase, Vercel e Upstash Redis. Estes fornecedores têm as suas próprias políticas. A localização GPS não é partilhada.", legal: "6. Finalidade e base legal", legalText: "Os dados servem para planeamento de rotas, previsões, alertas e contas. A base legal depende do serviço; a localização voluntária baseia-se no consentimento e a conta pode basear-se na execução de um contrato.", rights: "7. Os seus direitos", rightsText: "Pode pedir acesso, retificação, eliminação ou limitação e opor-se quando aplicável. Contacte o responsável ou a autoridade de proteção de dados.", changes: "8. Alterações", changesText: "Esta política pode ser atualizada quando mudarem a aplicação, o tratamento ou os serviços externos.", draft: "Este é um modelo de trabalho. Preencha os dados do responsável e peça revisão jurídica antes do uso público.",
  },
  sv: {
    title: "Integritetspolicy", back: "Tillbaka till appen", updated: "Senast uppdaterad: 10 juli 2026", admin: "1. Personuppgiftsansvarig", warning: "Fyll i ansvarigs fullständiga namn, adress och e-post för integritetsfrågor innan publicering.", adminText: `Ansvarig: ${common.owner}, kontakt: ${common.email}.`, data: "2. Uppgifter vi behandlar", dataText: "Vi behandlar enhetens position under aktivt körläge, en ruttfil eller länk, webbläsarinställningar, kontouppgifter och tekniska uppgifter som behövs för drift och säkerhet.", location: "3. Position och körläge", locationText: "Positionen läses först efter att användaren klickat på ‘Starta’ och godkänt webbläsarens åtkomst. Den används för kartan, framsteg och varningar. GPS skickas inte till vårt API och sparas inte på vår server.", storage: "4. Rutter och webbläsarlagring", storageText: "Senaste rutt och inställningar kan sparas lokalt i webbläsaren. Vi sparar dem inte på servern. De kan raderas genom att rensa webbplatsdata.", services: "5. Externa tjänster", servicesText: "Appen kan använda Open-Meteo, OpenStreetMap/Overpass, Google Maps/BRouter, Supabase, Vercel och Upstash Redis. Leverantörerna har egna policyer. GPS-position delas inte med dem.", legal: "6. Ändamål och rättslig grund", legalText: "Uppgifter används för ruttplanering, prognoser, varningar och konton. Grunden beror på tjänsten; frivillig position bygger på samtycke och konto kan bygga på avtal.", rights: "7. Dina rättigheter", rightsText: "Du kan begära tillgång, rättelse, radering eller begränsning och invända när det gäller. Kontakta ansvarig eller din dataskyddsmyndighet.", changes: "8. Ändringar", changesText: "Policyn kan uppdateras när appen, behandlingen eller externa tjänster ändras.", draft: "Detta är ett arbetsutkast. Fyll i ansvarigs uppgifter och låt texten granskas juridiskt före offentlig användning.",
  },
  ua: {
    title: "Політика конфіденційності", back: "Повернутися до застосунку", updated: "Останнє оновлення: 10 липня 2026 року", admin: "1. Власник даних", warning: "Перед публікацією заповніть повне ім’я, адресу та електронну пошту власника даних.", adminText: `Власник даних: ${common.owner}, контакт: ${common.email}.`, data: "2. Дані, які ми обробляємо", dataText: "Ми обробляємо місцезнаходження пристрою під час активної поїздки, переданий файл або посилання на маршрут, налаштування браузера, дані облікового запису та технічні дані для роботи й безпеки застосунку.", location: "3. Місцезнаходження та режим поїздки", locationText: "Місцезнаходження отримується лише після натискання «Почати» та дозволу браузера. Воно потрібне для карти, прогресу й попереджень. GPS не надсилається до нашого API та не зберігається на сервері.", storage: "4. Маршрути та пам’ять браузера", storageText: "Останній маршрут і налаштування можуть зберігатися локально в браузері. Ми не зберігаємо їх на сервері. Видалити їх можна, очистивши дані сайту.", services: "5. Зовнішні сервіси", servicesText: "Застосунок може використовувати Open-Meteo, OpenStreetMap/Overpass, Google Maps/BRouter, Supabase, Vercel та Upstash Redis. Ці постачальники мають власні політики. GPS не передається цим сервісам.", legal: "6. Мета та правова підстава", legalText: "Дані потрібні для планування маршруту, прогнозу, попереджень та облікових записів. Правова підстава залежить від послуги; добровільне місцезнаходження ґрунтується на згоді, а обліковий запис може ґрунтуватися на виконанні договору.", rights: "7. Ваші права", rightsText: "Ви можете вимагати доступу, виправлення, видалення або обмеження обробки даних та заперечувати, якщо це застосовно. Зверніться до власника даних або органу захисту даних.", changes: "8. Зміни", changesText: "Політика може оновлюватися у разі зміни застосунку, обробки даних або зовнішніх сервісів.", draft: "Це робочий шаблон. Перед публічним використанням заповніть дані власника та перевірте текст із юристом.",
  },
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return <section><h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">{title}</h2><p className="mt-2">{children}</p></section>;
}

export function PrivacyContent() {
  const { lang } = useLang();
  const copy = COPY[lang];

  return (
    <main className="min-h-screen overflow-y-auto bg-slate-50 px-4 py-8 text-slate-900 dark:bg-slate-950 dark:text-slate-100 sm:px-6">
      <article className="mx-auto max-w-3xl rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-10">
        <Link href="/" className="text-sm font-semibold text-cyan-600 hover:underline dark:text-cyan-400">← {copy.back}</Link>
        <h1 className="mt-6 text-3xl font-bold tracking-tight">{copy.title}</h1>
        <p className="mt-2 text-sm text-slate-500 dark:text-slate-400">{copy.updated}</p>
        <div className="mt-8 space-y-8 text-sm leading-6 text-slate-700 dark:text-slate-300">
          <section>
            <h2 className="text-lg font-semibold text-slate-900 dark:text-slate-100">{copy.admin}</h2>
            <p className="mt-2 rounded-lg border border-amber-300 bg-amber-50 p-3 text-amber-900 dark:border-amber-400/40 dark:bg-amber-400/10 dark:text-amber-200">{copy.warning}</p>
            <p className="mt-2">{copy.adminText}</p>
          </section>
          <Section title={copy.data}>{copy.dataText}</Section>
          <Section title={copy.location}>{copy.locationText}</Section>
          <Section title={copy.storage}>{copy.storageText}</Section>
          <Section title={copy.services}>{copy.servicesText}</Section>
          <Section title={copy.legal}>{copy.legalText}</Section>
          <Section title={copy.rights}>{copy.rightsText}</Section>
          <Section title={copy.changes}>{copy.changesText}</Section>
          <p className="border-t border-slate-200 pt-5 text-xs text-slate-500 dark:border-slate-800 dark:text-slate-400">{copy.draft}</p>
        </div>
      </article>
    </main>
  );
}
